language: node_js
matrix:
  include:
  - node_js:
    - '6'
    env:
    - CAN_DEPLOY=true
script: npm test && npm run build && npm run build:storybook
notifications:
  email:
    on_success: never
deploy:
  - provider: npm
    email: accounts@resin.io
    skip_cleanup: true
    api_key:
      secure: tL6tRzDN2331z1yik1UQtH3sKbMtcdqVXO2DNQgrr55/4x5fAq76ZB/pkW4Iiafopb4+OP03CN5Koo+loBDt6MXwi08k/oJwUkPyU3VqAC9AL3RwhPLuSTKQNCeZ/ALQYN2y0kPCr2z1GAvijXPQMzhNJK7nIhWgi6JXMKkxC9K7rVLazJwF4F0ZTYOpI9CCix1kbJfVHwnAX05EDXhdXsvoBLSmBPCAAPJmkOaPgmFsCnoJLXuCJjkBj69pyarwAolAEckrX5Fh6T72+B7NiMZaAAX53rTxZJCyWhKk/kClTBnIBYW35YufCIg+NTHPTrEwyYU+ouUHAsIzRE8TMWUuooolgWmC4ZozR2uphIu5uIWSSRzUlJgQ8z3T1ZOz+KCnSo/H3Si5gurzDSkQ2i9jZLI/B1oCq7DHYdMhC6T8HJnpF1KU3A2n52NWdTvFzD9ws8MtTM7ugBtEGrg/X/+9iTK0Sj+8OWOtnFHxcuTdTcke5A0S2KmgREss1cehYM0PxmGuxbLMe6ZcYAZ0xqhtp4OkjRN0bczymbvPcZqZhwvIbfjD4p1k1xMhtZjlmha15v9hSxNV8mEd/yptFle+f+E7bw1aRPjJFSS6kwxiQqhX8GyEjtiqFPCcUhL+FY9t70gpN6LA3fIdOct5+6KQiS4A1dIotsGuiMqgqPw=
    on:
      tags: true
      condition: $CAN_DEPLOY = 'true' && $TRAVIS_TAG =~ ^v?[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+
      repo: resin-io-modules/rendition
  - provider: pages
    local_dir: .out
    skip_cleanup: true
    github_token: $GH_TOKEN
    on:
      branch: master
      tags: true
      condition: $CAN_DEPLOY = 'true' && $TRAVIS_TAG =~ ^v?[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]+
env:
  global:
    secure: RMI57fdrPztupNdU2b1whQ50z69mGzCztG4vrSe+Q/FBBz0xSWsGlAEfIrKEq47m5vGXRSD3A7Uz+8FOdvnW13tl1BB33LbilWz4dnmQUdxTpUsVcti0kWkzkfac7BWg+gkbMxe+SmSi+c6XylzSJLnjXrm/SjGSLZW7gdYJaYHtkXcp788MIonxB3ICfWyh9fPE6/AqfHfMLDWGcYlZs0CiyXFfNIqwzL1BnKsIcGoSVSPBLQBXuvfeW7Jg9DFxZ9RYq71xgC2RecfYEdHimstTCC8agfZdFdNxA069bhuxljkcqKA7jhcN9D13/YAtFzhqE9jb31likgNUeGtFgkbQM35xkQ2+p5GxKcFuKXcO/6y+X5Lk57HgGEKHLg4bEXvGMzho0zAKd8U7qGI5RpITvO9ffEbcn99Qjzh0tByfzhbeb8rNXv0JlocOgPipxIQoh/w8oMxtX0C39J67RVQv2G1VixWS8AiRXMiZS0ahJG7e2PmgsRQM1zs74OGcsU8zC2dltTAcgDeDqzr/NXmQLSW4Gp/Lg5H7EpscNXXQcdmVMHVCapNzqjVVXOeqzles0d/M2K/EpVp8+uo3BQKczVVCxN2zm5JEfNBG+EQuCbE9HN+kToX6DF6UXS7t+hN2Sr6p+TPryttnvTYoi4wCQvENz5v61DL052n5nH4=
