language: node_js
node_js:
  - "7"

notifications:
  email:
    on_success: never

after_success:
  - if [[ ${TRAVIS_PULL_REQUEST} == "false" && ${TRAVIS_BRANCH} == "master" ]]; then
      npm run publish-storybook;
    fi
